---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
env:
  - CONSUL_VERSION=1.4.4
before_install:
  - gem install bundler -v 2.0.1
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir -p ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"
  - consul version
  - consul agent -dev >/dev/null 2>&1 &
script:
  - bundle exec rake spec
