default: &default
  consul:
    host: localhost
    port: 8500
  group: staging
  registry: Dryad::Consul::ServiceRegistry

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default